# Generated by Django 4.2.7 on 2023-12-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept_info',
            name='dept_start_date',
            field=models.DateField(default='2023-12-10'),
        ),
    ]
